<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: http://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/


// this is designed to push add the custom theme stylesheet after woocommerce.

function enqueue_style_after_wc() {

  // include the css file as a time version

 // vars
  $cssFileURI = get_stylesheet_directory_uri() . '/dist/main.min.css';
  $ver =  time();

  wp_enqueue_style( 'tightlines-jewelry-theme', $cssFileURI, [], $ver );

}

add_action('wp_enqueue_scripts', 'enqueue_style_after_wc', 20 );


/**
 * Remove the product schema markup from the Shop and Product Category pages.
 *
 * @link: https://www.checkerboard.com/web-development/fix-offers-review-aggregaterating-specified/
 *
 */
function wc_remove_product_schema_product_archive() {

    remove_action( 'woocommerce_shop_loop', array( WC()->structured_data, 'generate_product_data' ), 10, 0 );
}

add_action( 'woocommerce_init', 'wc_remove_product_schema_product_archive' );





// include the javascript file with a time version

   // vars
    $jsFileURI = get_stylesheet_directory_uri() . '/dist/app.min.js';
    $ver =  time();

wp_enqueue_script( 'site_main_js', $jsFileURI , null, $ver, true );

/**
 * Add Options Page i.e. Theme Settings Tab with ACF
 */
if( function_exists('acf_add_options_page') ) {

  acf_add_options_page(
      array(
          'page_title' => 'Theme General Settings',
          'menu_title' => 'Theme Settings',
          'menu_slug' => 'theme-general-settings',
          'capability' => 'edit_posts',
          'position' => 58,
          'icon_url' => false

      ));
}


/**
 * Post meta ... Now Search Meta
 * Function to build search results from top search bar, returning product posts.
 * If no image available, it will return a date, assuming it is a blog post or event instead.
 */

function search_meta() {

    // Evaluate if a post image exists

    if ( has_post_thumbnail() ) :

        // If so, return the thumbnail
    ?>
    <div class="product-thumbnail">
        <?php
        $post_id = get_the_ID();
        $thumb_id = get_post_thumbnail_id();
        $alt = get_post_meta( $thumb_id, '_wp_attachment_image_alt', true );

        $image_alt = ( $thumb_id = "" ? "Tightlines Jewelry" : $alt );

        echo '<a href="' . esc_url( get_permalink() ) . '" rel="bookmark" >';
        echo get_the_post_thumbnail( $post_id, 'thumbnail', array( 'class' => 'alignleft ', 'alt' => $image_alt  ) );
        echo '</a></h2>';
        ?>
    </div>

    <?php else :

        // Otherwise return the date format

        ?>
        <div class="date">
            <?php
            echo '<span class="day">' . esc_html( get_the_date( 'd' ) ) . '</span>';
            echo '<span class="month">' . esc_html( get_the_date( 'M' ) ) . '</span>';
            ?>
        </div>
   <?php endif;
   ?>
    <div class="title">
        <?php

        // placing the excerpt below the entry title. The second title appears most often

        if ( is_single() ) :

            the_title( '<h1 class="entry-title">', '</h1>' );
            the_excerpt();

        else :

            the_title( '<h2 class="entry-title"><a href="' . esc_url( get_permalink() ) . '" rel="bookmark" class="link__title">', '</a></h2>' );
            the_excerpt();

        endif;
        ?>
    </div>

    <?php
}

